Selector:
  Enabled: true
  Item: "BOOK"
  Name: "&f(*) &6&lServer-Selector &f(*)"
  Slot: 0
  Lore:
    - "&f&m-----------------------------"
    - "&7&oSelect a server to go to..."
    - "&f&m-----------------------------"

Hub:
  Enabled: true
  Item: "NETHER_STAR"
  Name: "&f(*) &b&lHub-Selector &f(*)"
  Slot: 1
  Lore:
    - "&f&m-----------------------------------"
    - "&7&oSelect a hub server to go to..."
    - "&f&m-----------------------------------"
EnderButt:
  Enabled: true
  Item: "ENDER_PEARL"
  Name: "&f(*) &b&lEnderButt &f(*)"
  Slot: 2
  Lore:
    - "&f&m-----------------------------------"
    - "&7&oRight click to fly..."
    - "&f&m-----------------------------------"

Inventory:
  Selector:
    Title: "&aServer Inventory"
    Slots: 9
    Items:
      1:
        Item: "DIAMOND_SWORD"
        Name: "&aHCF"
        Lore:
          - "&f&m-------------------------------"
          - "&7&oright click to join hcf queue"
          - "&f&m-------------------------------"
        Slot: 3
        Commands:
          - "play hcf"
  Hub:
    Title: "&aHub Inventory"
    Slots: 9
    Items:
      1:
        Item: "ENDER_PEARL"
        Name: "&aHub 01"
        Lore:
          - "&f&m-------------------------------"
          - "&7&oright click to join hub queue"
          - "&f&m-------------------------------"
        Slot: 3
        Commands:
          - "play hub1"

Spawn:
  Enabled: true
  x: 0
  y: 100
  z: 0

TabList:
  Left:
    0: "<player>"
    1: ""
    2: ""
    3: ""
    4: ""
    5: ""
    6: ""
    7: ""
    8: ""
    9: ""
    10: ""
    11: ""
    12: ""
    13: ""
    14: ""
    15: ""
    16: ""
    17: ""
    18: ""
    19: ""
  Middle:
    0: "<rank>"
    1: ""
    2: ""
    3: ""
    4: ""
    5: ""
    6: ""
    7: ""
    8: ""
    9: ""
    10: ""
    11: ""
    12: ""
    13: ""
    14: ""
    15: ""
    16: ""
    17: ""
    18: ""
    19: ""
  Right:
    0: "<online_players>"
    1: ""
    2: ""
    3: ""
    4: ""
    5: ""
    6: ""
    7: ""
    8: ""
    9: ""
    10: ""
    11: ""
    12: ""
    13: ""
    14: ""
    15: ""
    16: ""
    17: ""
    18: ""
    19: ""