take-damage-entity: false
take-damage: false
build-blocks: false
break-blocks: false
pickup-items: false
drop-items: false
join-message: true
No-Weather: true
No-Food: true
Chat: true
Mobs-Spawn: false
Luchpads: true
Doublejump: true
Fireworks: true
# We are currently supporting EzQueue || Portal ... However if your queue isn't on supported. Leave it blank... It will just not showcase the queue name // position on scoreboard
Queue: "NONE"
